apiVersion: platform.acme.co/v1alpha1
kind: Network
metadata:
  name: network1
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    autoCreateSubnetworks: false
    routingMode: "GLOBAL"
